language: android

android:
  components:
      - platform-tools
      - tools
      - build-tools-26.0.2
      - android-26
      - extra-android-m2repository
      # Specify at least one system image,
jdk:
  - oraclejdk8
  
env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=10
  
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build
