language: android

android:
  components:
      - platform-tools
      - tools
      - build-tools-28.0.3
      - android-28
      - extra-android-m2repository
      # Specify at least one system image,

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

jdk:
  - oraclejdk8
  
env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=10
  
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build
