language: android

android:
  components:
      - platform-tools
      - tools
      - build-tools-26.0.2
      - android-26
      - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
